### ISSUE TITLE
Doesn't work for me on OS X

### ISSUE THREAD

**Issue by dankohn** [flavorjones/chromedriver-helper#11]
Hi, chromedriver-helper didn't work for me on OS X. Instead, `brew install chromedriver` worked fine. Sorry, I'm not sure how to debug the problem, but I wanted to let you know.

```
unable to connect to chromedriver http://127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.42.0/lib/selenium/webdriver/chrome/service.rb:50:in `start'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.42.0/lib/selenium/webdriver/chrome/bridge.rb:15:in `initialize'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.42.0/lib/selenium/webdriver/common/driver.rb:37:in `new'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.42.0/lib/selenium/webdriver/common/driver.rb:37:in `for'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/selenium-webdriver-2.42.0/lib/selenium/webdriver.rb:67:in `for'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/selenium/driver.rb:13:in `browser'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/selenium/driver.rb:69:in `find_xpath'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/node/base.rb:107:in `find_xpath'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/query.rb:110:in `block in resolve_for'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/node/base.rb:80:in `synchronize'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/query.rb:106:in `resolve_for'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/node/matchers.rb:122:in `block in assert_no_selector'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/node/base.rb:84:in `synchronize'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/node/matchers.rb:121:in `assert_no_selector'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/session.rb:675:in `block (2 levels) in <class:Session>'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/session.rb:104:in `reset!'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara.rb:257:in `block in reset_sessions!'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara.rb:257:in `each'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara.rb:257:in `reset_sessions!'
      /Users/dan/.rvm/gems/ruby-2.1.2/gems/capybara-2.4.1/lib/capybara/cucumber.rb:8:in `After'
```

Also:

```
$ chromedriver-update 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: http
/Users/dan/.rvm/gems/ruby-2.1.2/gems/chromedriver-helper-0.0.5/lib/chromedriver/helper.rb:23:in `block in download': Could not download http: (RuntimeError)
    from /Users/dan/.rvm/gems/ruby-2.1.2/gems/chromedriver-helper-0.0.5/lib/chromedriver/helper.rb:20:in `chdir'
    from /Users/dan/.rvm/gems/ruby-2.1.2/gems/chromedriver-helper-0.0.5/lib/chromedriver/helper.rb:20:in `download'
    from /Users/dan/.rvm/gems/ruby-2.1.2/gems/chromedriver-helper-0.0.5/lib/chromedriver/helper.rb:31:in `update'
    from /Users/dan/.rvm/gems/ruby-2.1.2/gems/chromedriver-helper-0.0.5/bin/chromedriver-update:5:in `<top (required)>'
    from /Users/dan/.rvm/gems/ruby-2.1.2/bin/chromedriver-update:23:in `load'
    from /Users/dan/.rvm/gems/ruby-2.1.2/bin/chromedriver-update:23:in `<main>'
    from /Users/dan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by aruprakshit** [comment]
@flavorjones I am using this version `'chromedriver-helper', '~> 1.0'` and still getting the same issue OP asked.

```
the signin process
2017-06-27 18:42:12 WARN Selenium [DEPRECATION] :args or :switches is deprecated. Use Selenium::WebDriver::Chrome::Options#add_argument instead.
  signs me in (FAILED - 1)

Failures:

  1) the signin process signs me in
     Failure/Error: visit '/'

     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:9515
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:130:in `connect_until_stable'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:74:in `block in start'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:71:in `start'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/chrome/driver.rb:52:in `initialize'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/driver.rb:46:in `new'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/driver.rb:46:in `for'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver.rb:86:in `for'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/capybara-2.14.3/lib/capybara/selenium/driver.rb:23:in `browser'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/capybara-2.14.3/lib/capybara/selenium/driver.rb:67:in `visit'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/capybara-2.14.3/lib/capybara/session.rb:269:in `visit'
     # /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/capybara-2.14.3/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/signin_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 20.27 seconds (files took 0.55112 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/signin_spec.rb:5 # the signin process signs me in

/Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515) (Errno::ECONNREFUSED)
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/arup/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:93:in `connect_to_server'
	from /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:116:in `stop_server'
	from /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:79:in `stop'
	from /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/service.rb:69:in `block in start'
	from /Users/arup/.rvm/gems/ruby-2.3.3@e2e-dockingtest-app/gems/selenium-webdriver-3.4.3/lib/selenium/webdriver/common/platform.rb:138:in `block in exit_hook'
```

**Comment by flavorjones** [comment]
@aruprakshit thanks for asking this question. It's considered poor form, though, to comment on a closed issue. This issue in particular has been closed for over three years.

Can you please open a new issue?

**Comment by aruprakshit** [comment]
@flavorjones I will do. I thought to not duplicate the same issue in multiple tickets.
