### ISSUE TITLE
Using with Rails: "uninitialized constant Selenium"

### ISSUE THREAD

**Issue by mattbrictson** [flavorjones/chromedriver-helper#60]
I just upgraded an existing Rails app to chromedriver-helper 2.0, and upon running my app I get this error:

```
bundler-1.16.4/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require':
There was an error while trying to load the gem 'chromedriver-helper'.
Gem Load Error is: uninitialized constant Selenium
Backtrace for gem load error is:
chromedriver-helper-2.0.0/lib/chromedriver-helper.rb:1:in `<top (required)>'
```

Workaround: place the `chromedriver-helper` gem *after* selenium in app's Gemfile. E.g.

```
group :test do
  gem "selenium-webdriver"
  gem "chromedriver-helper" # must load after selenium
end
```

**Comment by artplan1** [comment]
Another possible workaround (it doesn't hurt rubocop's order rule) is to require manually in `<rails/spec/capybara>_helper`

```ruby
require 'selenium/webdriver'
require 'chromedriver-helper'
```

and `require: false` in gemfile

```ruby
gem 'chromedriver-helper', require: false
gem 'selenium-webdriver', require: false
```

**Comment by flavorjones** [comment]
Seems easy to fix, let me repro and cut a patch release.

**Comment by flavorjones** [comment]
@markedmondson Please see comments in #61 about this; it's possible to run chromedriver-helper as a standalone gem that doesn't need selenium-webdriver.
